src/main/java/com/ostphoto/app/admin/news/domain/Article.java
package com.ostphoto.app.admin.news.domain;

import com.ostphoto.app.admin.photo.domains.SimplePhoto;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@Entity
public class Article {

    @Id
    @GeneratedValue
    private int id;

    @NotNull
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    @Column(name = "created", nullable = false)
    @Type(type = "org.joda.time.contrib.hibernate.PersistentDateTime")
    private DateTime date;

    @Column(name = "title", nullable = false)
    private String title;

    @Column(name = "body", nullable = false, length = 5000)
    private String body;

    @ManyToOne
    @JoinColumn(name="cover_id")
    private SimplePhoto cover;

    @Column(name = "shortDescription", nullable = false)
    private String shortDescription;



    public Article() {
    }

    @PrePersist
    protected void onCreate() {
        date = DateTime.now();
    }

    public Article(int id, String title, String shortDescription, DateTime date) {
        this.id = id;
        this.title = title;
        this.shortDescription = shortDescription;
        this.date = date;
    }

    public Article(String title, String shortDescription,  String body, DateTime date) {
        this.title = title;
        this.shortDescription = shortDescription;
        this.body = body;
        this.date = date;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

/*    public void setDate(LocalDate date) {
        this.date = date;
    }*/

    public DateTime getDate() {
        return date;
    }

    public String getMonth() {
        return date.monthOfYear().getAsShortText();
    }

    public int getDay() {
        return date.getDayOfMonth();
    }

    public void setDate(DateTime date) {
        this.date = date;
    }

    public SimplePhoto getCover() {
        return cover;
    }

    public void setCover(SimplePhoto cover) {
        this.cover = cover;
    }

    public String getShortDescription() {
        return shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }



}

src/main/java/com/ostphoto/app/admin/news/NewsAdminController.java
package com.ostphoto.app.admin.news;

import com.ostphoto.app.admin.BaseAdminController;
import com.ostphoto.app.admin.news.domain.Article;
import com.ostphoto.app.admin.news.service.NewsService;
import org.joda.time.DateTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Locale;

/**
 * Created by mxostrov on 05.04.14.
 */
@Controller
@RequestMapping(value = "/admin/news")
public class NewsAdminController implements BaseAdminController {

    @Autowired
    private NewsService newsService;

    @Override
    @RequestMapping(method = RequestMethod.GET)
    public String start(Locale locale, Model model) {
        List<Article> news = newsService.findAll();
        news.add(new Article(1, "A new site is about to open soon", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                DateTime.now()));
        model.addAttribute("newsList", news);
        return NewsModule.NEWS_ADMIN_VIEW;
    }

    @RequestMapping(value = "/{id}")
    public String fullArticle( Model model, @PathVariable("id") int id) {
        Article article = newsService.getById(id);
        model.addAttribute("article",  article);
        return "/admin/article";
    }


    @RequestMapping(value = "/get/{id}")
    @ResponseBody
    public Article getArticle(Model model, @PathVariable("id") int id) {
        Article article = newsService.getById(id);
        return article;
    }



    @RequestMapping(value = "/save", method = RequestMethod.POST)
    @ResponseBody
    public boolean saveArticle(@RequestBody Article article, BindingResult bindingResult, Model model)  {
        article.setDate(DateTime.now());
        return  newsService.save(article);

    }

}

src/main/java/com/ostphoto/app/site/calendar/BookingController.java
package com.ostphoto.app.site.calendar;

import com.ostphoto.app.admin.calendar.CalendarModule;
import com.ostphoto.app.admin.calendar.domain.Meeting;
import com.ostphoto.app.admin.calendar.service.MeetingService;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;
import org.joda.time.LocalTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.validation.Valid;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import static com.ostphoto.app.util.Responses.FAILURE;
import static com.ostphoto.app.util.Responses.SUCCESS;
import static com.ostphoto.app.util.Responses.responseWithErrors;

@Controller
public class BookingController {

    public static final String BOOKING_VIEW = "client/booking";

    @Autowired
    private MeetingService meetingService;

    @RequestMapping(value = "/booking", method = RequestMethod.GET)
    public String home(Locale locale, Model model) {
        model.addAttribute(CalendarModule.ATTRIBUTE_MEETING_FORM, new Meeting());
        return BOOKING_VIEW;
    }

    @RequestMapping(value = "/booking/all", method = RequestMethod.GET)
    @ResponseBody
    public List<LocalDate> getBusyDays() {
        return meetingService.findBusyDays();
    }

    @RequestMapping(value = "/booking/add", method = RequestMethod.POST)
    @ResponseBody
    public Map<String, Object> addMeeting(Meeting meeting) {
        meeting.setId(0);
        meeting.setConfirmed(false);
        return responseWithErrors(meetingService.save(meeting));
    }

    @RequestMapping(value = "/booking/freetime/{date}", method = RequestMethod.GET)
    @ResponseBody
    public Map<LocalTime, Boolean> freeTimeByDate(@PathVariable("date") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) DateTime date) {
        return meetingService.getFreeTimeByDate(date);
    }
}

src/main/webapp/WEB-INF/views/client/about.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" session="false" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%response.setHeader("Pragma", "no-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);%>
<t:page currentPage="about">
    <jsp:attribute name="head">
        <title>Ostphoto: Contact Us</title>
    </jsp:attribute>
    <jsp:attribute name="javascript">

    </jsp:attribute>
    <jsp:body>
        <div class="container min-height">


        <div class="row col-sm-12">
            <div class="col-sm-12 col-sm-12">
                <h2>Contact us</h2>

                <div class="hr-header">
                    <div></div>
                </div>
            </div>
        </div>
        <div class="row pad-md-bottom col-sm-12">
            <div class="col-sm-12">
                <p>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. </p>
            </div>
        </div>
        <div class="row col-sm-12">
            <div class="col-sm-3">
                <h3>Address</h3>
            </div>
            <div class="col-sm-4"></div>
            <div class="col-sm-5">
                <h3>Ask a question</h3>
            </div>
        </div>
        <div class="row pad-md-bottom col-sm-12">
            <div class="col-sm-3">
                <p>
                    Russian Federation
                </p>
                <p>
                    <small>Nizhnyi Novgorod, <br> 34, 92, bld. 112, 60 let Oktyabrya str.</small>
                </p>
                <div class="row">
                    <div class="col-sm-offset-1">
                        <ul class="list-unstyled">
                            <li class="pad-sm-bottom"><i class="fa fa-phone"></i> (831) 412-34-56</li>
                            <li class="pad-sm-bottom"><i class="fa fa-envelope"></i> <a href="mailto:admin@ostphoto.pro">admin@ostphoto.pro</a></li>
                            <li class="pad-sm-bottom"><i class="fa fa-skype"></i> Ostphoto52</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <script charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=1SYe6ugION5HlnAE1AWmMFeZA2DKc1Mt&height=350"></script>
            </div>
            <div class="col-sm-5">
                <form class="form-inline">
                    <div class="row pad-sm-bottom">
                        <div class="form-group col-sm-6">
                            <label class="sr-only" for="contact-name">Name</label>
                            <input type="text" class="form-control" id="contact-name" placeholder="Name">
                        </div>
                        <div class="form-group col-sm-6">
                            <label class="sr-only" for="contact-phone">Phone</label>
                            <input type="text" class="form-control" id="contact-phone" placeholder="Phone number">
                        </div>
                    </div>
                    <div class="row pad-sm-bottom">
                        <div class="col-sm-12">
                            <label class="sr-only" for="contact-message">Message</label>
                            <textarea class="form-control" id="contact-message" placeholder="Leave your message"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="submit" class="btn btn-primary center-block" value="Send">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </jsp:body>
</t:page>

src/main/webapp/WEB-INF/views/client/booking.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" session="false" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<t:page currentPage="booking">
    <jsp:attribute name="head">
        <title>Ostphoto: booking the photosession</title>
        <link rel="stylesheet/less" href="${pageContext.request.contextPath}/resources/less/partial/calendar.less"/>
        <link rel="stylesheet/less" href="${pageContext.request.contextPath}/resources/less/partial/meeting.less"/>
    </jsp:attribute>
    <jsp:attribute name="javascript">
        <script src="${pageContext.request.contextPath}/resources/plugins/clndr/js/clndr.js"></script>
        <script src="${pageContext.request.contextPath}/resources/js/calendar.js"></script>
        <script src="${pageContext.request.contextPath}/resources/js/meeting.js"></script>
        <script src="${pageContext.request.contextPath}/resources/js/booking.js"></script>
    </jsp:attribute>
    <jsp:body>
        <div class="container min-height">


        <t:calendar cssClass="big-calendar row-divider col-sm-12">
            <jsp:attribute name="navigation">
                <div class="clndr-controls row">
                    <div class="col-xs-3"><h2>{{ month }}</h2></div>
                    <div class="col-xs-offset-10 clndr-control-buttons">
                        <button class="btn btn-default clndr-previous-button col-sm-6">
                            <i class="fa fa-long-arrow-left fa-lg"></i>
                        </button>
                        <button class="btn btn-default clndr-next-button col-sm-6">
                            <i class="fa fa-long-arrow-right fa-lg"></i>
                        </button>
                    </div>
                </div>
                <div class="hr-header">
                    <div></div>
                </div>
            </jsp:attribute>
        </t:calendar>
        </div>
    </jsp:body>
</t:page>

src/main/webapp/WEB-INF/views/client/gallery.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" session="false" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%
    response.setHeader("Pragma", "no-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
%>
<t:page currentPage="portfolio">
    <jsp:attribute name="head">
    <link rel="stylesheet/less" type="text/css" href="${pageContext.request.contextPath}/resources/less/partial/portfolio.less"/>
    </jsp:attribute>
    <jsp:attribute name="javascript">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
      <script src="${pageContext.request.contextPath}/resources/plugins/yoxview/jquery.yoxview-2.21.min.js"></script>
         <script type="text/javascript">

    jQuery(document).ready(function ($) {
        jQuery.noConflict();

        jQuery(".yoxview").yoxview({
                    autoHideMenu: false
                }
        );

    });
</script>
    </jsp:attribute>

    <jsp:body>
        <div class="container min-height">
        <div class="row">
            <div class="col-lg-12 yoxview">
                <h2>${cat.name}</h2>

                <div class="hr-header marginBottom10">
                    <div></div>
                </div>
                <p class="pad-md-bottom">${cat.comment}</p>

                <c:forEach items="${cat.photos}" var="photo">
                    <c:if test="${!photo.hide}">
                     <div class="col-xs-2 pad-md-bottom">
                         <a href="${pageContext.request.contextPath}/photo/ORIGINAL/${photo.upldate}/${photo.fileName}"  title="<h3>${photo.title}</h3><p>${photo.title}</p>">
                         <t:img photo="${photo}" size="LAST" classStyle="img-responsive"/>
                             </a>
                    </div>
                    </c:if>
                </c:forEach>



<%--
                <ul class="list-unstyled photos">
                    <c:forEach items="${photos}" var="photo">

                        <li class="col-sm-3">
                            <a href="${pageContext.request.contextPath}/admin/photo/ORIGINAL/${photo.upldate}/${photo.fileName}" data-lightbox="last" title="Title">
                                <img src="${pageContext.request.contextPath}/admin/photo/last/${photo.upldate}/${photo.fileName}"/>
                            </a>
                        </li>

                    </c:forEach>
                </ul>--%>
            </div>

        </div>
        </div>
    </jsp:body>
</t:page>

src/main/webapp/WEB-INF/views/client/index.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" session="false" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%
    response.setHeader("Pragma", "no-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
%>
<t:page currentPage="index">
    <jsp:attribute name="head">
        <link rel="stylesheet/less" href="${pageContext.request.contextPath}/resources/less/partial/calendar.less"/>
        <link rel="stylesheet/less" href="${pageContext.request.contextPath}/resources/less/partial/meeting.less"/>
        <link rel="stylesheet/less" href="${pageContext.request.contextPath}/resources/less/partial/slideshow.less"/>
        <link rel="stylesheet/less" href="${pageContext.request.contextPath}/resources/less/partial/news.less"/>
        <link rel="Stylesheet" type="text/css" href="${pageContext.request.contextPath}/resources/plugins/yoxview/yoxview.css">
    </jsp:attribute>
    <jsp:attribute name="javascript">
        <script src="${pageContext.request.contextPath}/resources/plugins/galleriffic/js/jquery.galleriffic.js"></script>
        <script src="${pageContext.request.contextPath}/resources/plugins/galleriffic/js/jquery.opacityrollover.js"></script>
        <script src="${pageContext.request.contextPath}/resources/plugins/clndr/js/clndr.js"></script>
        <script src="${pageContext.request.contextPath}/resources/js/index.js"></script>
        <script src="${pageContext.request.contextPath}/resources/js/meeting.js"></script>
        <script src="${pageContext.request.contextPath}/resources/js/calendar.js"></script>
        <script src="${pageContext.request.contextPath}/resources/js/booking.js"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script src="${pageContext.request.contextPath}/resources/plugins/yoxview/jquery.yoxview-2.21.min.js"></script>
<script type="text/javascript">

    jQuery(document).ready(function ($) {
        jQuery.noConflict();

        jQuery(".thumbnails.yoxview").yoxview({
                    autoHideMenu: false
                }
        );
        var  thumbs = $("#thumbs").find("img");
        var images = [];
        for(var i = 0; i<thumbs.length; i++) {
            function media(src, title) {
                this.src = src;
                this.title = title;
            }
            images.push({ media : { src :thumbs[i].getAttribute("original"), title : thumbs[i].getAttribute("title")}});
        }

        var yoxviewLink = jQuery(".yoxviewLink").yoxview({
                    autoHideMenu: false,
                    images: images
                }
        );

        jQuery(".yoxviewLink").click( function() {
            yoxviewLink.yoxview("select", parseInt( this.getAttribute("photo-id")));
        });
    });
</script>

     </jsp:attribute>
    <jsp:body>
        <div class="row background-cont pad-md-bottom row-shade-top"></div>
        <div class="row background-cont pad-md-bottom2 pad-md-top border-bottom">

            <div class="container-slideshow center-block">
                <div id="slider-scale" class="yoxview">
                    <a photo-id="0" class='yoxviewLink pointer' href="${pageContext.request.contextPath}/photo/original/${sliderCat.photos[0].upldate}/${sliderCat.photos[0].fileName}" ><span class="glyphicon glyphicon-search"></span></a>
                </div>
                <div id="slider-first-layer">
                    <div class="slideshow-image" id="slideshow"></div>
                    <div id="thumbs" class="navigation">
                        <ul class="thumbs list-unstyled">
                                    <c:forEach items="${category.photos}" var="photo">
                                        <c:if test="${!photo.hideForSlider}">
                                        <li>
                                            <a class="thumb" name="leaf" title="" href="${pageContext.request.contextPath}/photo/SLIDER/${photo.upldate}/${photo.fileName}">
                                                <img original="${pageContext.request.contextPath}/photo/ORIGINAL/${photo.upldate}/${photo.fileName}" photo-id="0" src="${pageContext.request.contextPath}/photo/SLIDERTH/${photo.upldate}/${photo.fileName}" title="${photo.title}"/>
                                            </a>
                                        </li>
                                        </c:if>
                                    </c:forEach>
                        </ul>
                    </div>
                </div>
                <c:if test="${not empty category.name}">
                <div class='slider-gallery-descr ${not empty category.comment ? "with-text" : ""}'>
                    <h4 style="height: 30px"> <a href="${pageContext.request.contextPath}/portfolio/${category.name}">${category.name}</a></h4>
                    <p style="height: 30px">
                    <c:choose>
                        <c:when test="${category.comment != null && fn:length(category.comment)>83}">
                            <c:set var="shortDescr" value='${fn:substring(category.comment, 0, 79)}' />
                            ${shortDescr}...
                        </c:when>
                        <c:otherwise>
                            ${category.comment}
                        </c:otherwise>
                    </c:choose>
                </p></div>
                </c:if>
            </div>
        </div>
        <div class="container pad-md-bottom2">
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <h2>Our news</h2>

                        <div class="hr-header">
                            <div></div>
                        </div>
                    </div>
                </div>
                <ul class="list-unstyled list-news">
                    <c:forEach items="${newsList}" var="article">
                        <li>
                            <div class="row">
                                <div class="col-sm-2">
                                    <span class="news-date">
                                        <span class="news-date-number">${article.day}</span>
                                        ${article.month}
                                    </span>
                                </div>
                                <div class="col-sm-10">
                                    <div class="news-text">
                                        <h4><a href="${pageContext.request.contextPath}/news/${article.id}">${article.title}</a></h4>
                                        <p>${article.shortDescription}</p>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </c:forEach>
                </ul>
            </div>
            <div class="col-sm-4">
                <t:calendar cssClass="small-calendar pad-sm-bottom">
                        <jsp:attribute name="navigation">
                            <div class="row text-center">
                                <div class="col-sm-12">
                                    <div class="col-sm-2 clndr-control clndr-controls clndr-previous-button">
                                        <i class="fa fa-angle-left"></i>
                                    </div>
                                    <div class="col-sm-8 clndr-controls">
                                        {{ month }}, {{ year }}
                                    </div>
                                    <div class="col-sm-offset-10 clndr-control clndr-controls clndr-next-button">
                                        <i class="fa fa-angle-right"></i>
                                    </div>
                                </div>
                            </div>
                        </jsp:attribute>
                </t:calendar>
                <button class="btn btn-primary btn-meeting col-sm-12">
                    <span class="glyphicon glyphicon-camera"></span> I want a photoshoot
                </button>
            </div>
        </div>
        <div class="background-cont pad-md-bottom2  pad-md-top border-top border-bottom">
            <div class="container">
                <h2>Last added photos</h2>
                <div class="hr-header">
                    <div></div>
                 </div>
                <ul class="list-inline recent-photos thumbnails yoxview">
                    <c:forEach items="${lastPhotos}" var="photo">
                        <li class="col-sm-3">
                            <a href="${pageContext.request.contextPath}/photo/ORIGINAL/${photo.upldate}/${photo.fileName}"  >
                                <img alt="" title='${not empty photo.title ? "<h4>".concat(photo.title).concat("</h4>") : ""}${not empty photo.description ? "<p>photo.description</p>" : ""}' class="img-responsive center-block" src="${pageContext.request.contextPath}/photo/LAST/${photo.upldate}/${photo.fileName}"/>
                            </a>
                        </li>
                    </c:forEach>
                </ul>
            </div>
        </div>
        </div>
    </jsp:body>
</t:page>

src/main/webapp/WEB-INF/views/client/news.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" session="false" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%
    response.setHeader("Pragma", "no-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
%>
<t:page currentPage="news">
    <jsp:attribute name="javascript">
        <script src="${pageContext.request.contextPath}/resources/plugins/bootpag/jquery.bootpag.min.js"></script>
   <script type="text/javascript">
 /*      $('#page-selection').bootpag({
           total: 9
*//*           page: 1,
           maxVisible: 6,
           href: "#page-{{number}}",
           leaps: false,
           next: 'next',
           prev: 'previous'*//*
       }).on('page', function (event, num) {
*//*                   $.ajax({
                       url:  '/news/page/' + num,
                       dataType: "json",
                       type: "get",
                       success: function (data, textStatus) {


                       },
                       error: function (xhr, status, error) {
                           $.error(error);
                       }
                   });*//*

               });*/
   </script>
    </jsp:attribute>
    <jsp:body>
        <div class="container min-height" style="margin-top:10px;">
            <div class="content">
             <c:forEach items="${newsList}" var="artticle">
                <t:article  article="${artticle}" />
            </c:forEach> </div>
  <%--          <div id="page-selection">Pagination goes here</div>--%>
         </div>
    </jsp:body>
</t:page>

src/main/webapp/WEB-INF/views/client/portfolio.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" session="false" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>


<%
    response.setHeader("Pragma", "no-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
%>
<t:page currentPage="portfolio">
    <jsp:attribute name="head">
        <link rel="stylesheet/less" type="text/css" href="${pageContext.request.contextPath}/resources/less/partial/portfolio.less"/>
    </jsp:attribute>

    <jsp:body>

        <div class="container  pad-md-top2 min-height" style="margin-top:10px;">
            <c:set var="count" value="1" />
                <c:forEach items="${catList}" var="cat" varStatus="varStatus">
                    <c:if test="${!cat.hide}">

                    ${(count + 1)  % 2 == 0 ? "<div class='row form-group'>" : ""}
                        <c:set var="photo" value="${cat.face}"/>
                        <div class="col-xs-12 col-md-6">
                            <div class="panel panel-default">
                                <a class="panel-image display-block" href="${pageContext.request.contextPath}/portfolio/${cat.name}">
                                    <t:img photo="${photo}" size="SLIDER" classStyle="panel-image-preview pointer"/>
                        <%--            <label for="toggle-${varStatus.count}" class="pointer"></label>--%>
                                </a>
                               <%--
                                <input type="checkbox" checked id="toggle-${varStatus.count}" class="panel-image-toggle">
--%>
                                <div class="panel-body">
                                    <h4 style="height: 30px"><a href="${pageContext.request.contextPath}/portfolio/${cat.name}">${cat.name}</a></h4>
                                    <p style="height: 30px">                    <c:choose>
                                        <c:when test="${cat.comment != null && fn:length(cat.comment)>130}">
                                            <c:set var="shortDescr" value='${fn:substring(cat.comment, 0, 126)}' />
                                            ${shortDescr}...
                                        </c:when>
                                        <c:otherwise>
                                            ${cat.comment}
                                        </c:otherwise>
                                    </c:choose></p>
                                </div>
                                <div class="panel-footer background-cont text-center">
                                    <a href="#twitter"><span class="fa fa-heart"></span></a>
                                    <a href="#share"><span class="glyphicon glyphicon-share-alt"></span></a>
                                </div>
                            </div>
                        </div>
                    ${(count + 1) % 2 != 0 ? "</div>" : ""}
                        <c:set var="count" value="${count + 1}" scope="page"/>
                    </c:if>
                </c:forEach>




            </div>
        </div>
    </jsp:body>
</t:page>